<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?> - Excel Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .filter-info {
            background-color: #f5f5f5;
            padding: 10px;
            margin-bottom: 20px;
            border-radius: 5px;
        }
        .filter-info h3 {
            margin-top: 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table th {
            background-color: #4CAF50;
            color: white;
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
        }
        table td {
            padding: 8px;
            border: 1px solid #ddd;
        }
        table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .result-positive {
            color: #d32f2f;
            font-weight: bold;
        }
        .result-negative {
            color: #388e3c;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1><?= $title ?></h1>
        <p>Sistem Prediksi Diabetes - Random Forest Model</p>
        <p>Export Date: <?= $export_date ?></p>
    </div>

    <?php if ($filters['start_date'] || $filters['end_date'] || $filters['id_pasien'] || $filters['hasil'] !== null): ?>
    <div class="filter-info">
        <h3>Filter Applied:</h3>
        <ul>
            <?php if ($filters['start_date']): ?>
                <li>Start Date: <?= $filters['start_date'] ?></li>
            <?php endif; ?>
            <?php if ($filters['end_date']): ?>
                <li>End Date: <?= $filters['end_date'] ?></li>
            <?php endif; ?>
            <?php if ($filters['id_pasien']): ?>
                <li>Patient ID: <?= $filters['id_pasien'] ?></li>
            <?php endif; ?>
            <?php if ($filters['hasil'] !== null && $filters['hasil'] !== ''): ?>
                <li>Result: <?= $filters['hasil'] == 1 ? 'Diabetes' : 'Not Diabetes' ?></li>
            <?php endif; ?>
        </ul>
    </div>
    <?php endif; ?>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Patient Name</th>
                <th>Date</th>
                <th>Pregnancies</th>
                <th>Glucose</th>
                <th>Blood Pressure</th>
                <th>Skin Thickness</th>
                <th>Insulin</th>
                <th>BMI</th>
                <th>DPF</th>
                <th>Age</th>
                <th>Result</th>
            </tr>
        </thead>
        <tbody>
            <?php $no = 1; ?>
            <?php foreach ($prediksi as $p): ?>
                <tr>
                    <td><?= $no++ ?></td>
                    <td><?= esc($p['nama_pasien']) ?></td>
                    <td><?= date('d-m-Y H:i', strtotime($p['created_at'])) ?></td>
                    <td><?= esc($p['pregnancies']) ?></td>
                    <td><?= esc($p['glucose']) ?></td>
                    <td><?= esc($p['blood_pressure']) ?></td>
                    <td><?= esc($p['skin_thickness']) ?></td>
                    <td><?= esc($p['insulin']) ?></td>
                    <td><?= esc($p['bmi']) ?></td>
                    <td><?= esc($p['dpf']) ?></td>
                    <td><?= esc($p['age']) ?></td>
                    <td class="<?= $p['hasil'] == 1 ? 'result-positive' : 'result-negative' ?>">
                        <?= $p['hasil'] == 1 ? 'Diabetes' : 'Not Diabetes' ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Diabetes Prediction System - CodeIgniter 4 + AdminLTE + Python Random Forest</p>
        <p>Total Records: <?= count($prediksi) ?></p>
    </div>
</body>
</html>
